### ISSUE TITLE
[Bug] Can not turn off the status bar. 

### ISSUE THREAD

**Issue by Drakemoor** [willasm/vc-weather#10]
As the title says. I turn off the setting but the status bar continues to show the weather.

**Comment by willasm** [comment]
Your right. I must have broken it when I added weather alerts? Should be easy enough to track down.

Thanks for the report, William.

**Comment by willasm** [comment]
Sorry for the delay but the latest release v0.2.4 fixes this issue. It also adds many other changes. The toggle setting to cycle the statusbar was also broken which no one else even noticed. Thanks for reporting this as it may have been quite aa while before I even noticed this otherwise. With the huge amount of changes I made it is always possible I may have introduced a new bug. If you spot anything please let me know.

Thank you for your report on this issue, William

**Comment by Drakemoor** [comment]
It is fixed for me. Thanks.

**Comment by willasm** [comment]
Plugin has now been added to the community plugins list. BRAT plugin is no longer required to install/update the plugin.

Thanks for all the input, William
